sudo: false

language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

env:
  global:
    - FLASK_APP=aerarium
    - SECRET_KEY="Gallia est omnis divisa in partes tres"

  matrix:
    - FLASK_DEBUG=1
    - FLASK_DEBUG=0


before_install:
  - cp instance/example.env instance/.env

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - flake8
  - flask translate compile
  - coverage run --source app --omit app/cli.py -m unittest discover -v -s tests -p "*_test.py" -t .
  - sphinx-apidoc -o docs/source/api app app/configuration
  - sphinx-build -b html docs/source docs/build

after_success:
- codecov
