sudo: false

language: python

python:
  - "3.6"

env:
  global:
    - FLASK_APP=aerarium
    - SECRET_KEY="Gallia est omnis divisa in partes tres"
    - SYS_ADMINS=aerarium@bastianmeyer.eu

  matrix:
    - FLASK_DEBUG=1
    - FLASK_DEBUG=0

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE aerarium_test;'
  - cp instance/example.env instance/.env
  - sed -i -e 's/# DATABASE_URI=/DATABASE_URI=mysql+pymysql:\/\/root@localhost\/aerarium_test/g' instance/.env

install:
  - pip install pipenv
  - pipenv sync
  - pipenv install codecov

script:
  - flake8
  - flask translate compile
  - flask db upgrade
  - coverage run -m unittest discover -v -s tests -p "*_test.py" -t .
  - sphinx-apidoc -o docs/source/api app app/configuration
  - sphinx-build -b html docs/source docs/build

after_success:
- codecov
